<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$whoops = new \Whoops\Run;
$whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);
$whoops->register();
//$repositories = $client->api('user')->repositories('ornicar');
//$repos = $client->api('search')->repositories('github language:java');
//$readme = $client->api('repo')->contents()->readme('KnpLabs', 'php-github-api');
//$repos2 = $client->api('repo')->find('symfony');
$path = 'pom.xml';
//$fileContent = $client->api('repo')->contents()->download('hankcs', 'HanLP', $path);
//$repos = $client->api('search')->repositories('github language:php');

//$composerJson = $client->api("repo")->contents()->download("wikimedia",$repos["items"][1]["name"], "composer.json");
//
//echo $composerJson;

//for ($i=0;$i<10;$i++){
//
//}
//
//echo json_encode($repos["items"][1]["name"]);

echo json_encode($searchLimit = $client->api('rate_limit')->getRateLimits());